### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by taqueci** [taqueci/redmine_share#2]
Error occurs in Redmine 4.1.
```
NoMethodError (undefined method `to_sym' for false:FalseClass
Did you mean? to_s):

lib/redmine/i18n.rb:111:in `valid_languages'
lib/redmine/i18n.rb:135:in `find_language'
app/controllers/application_controller.rb:206:in `set_localization'
```

**Comment by taqueci** [comment]
The issue will be solved by:
```diff
--- a/config/locales/no.yml
+++ b/config/locales/no.yml
@@ -1,4 +1,4 @@
-no:
+"no":
   share_button: Share
   share_title: "Share link" 
```
